version: "3.18"

services:
  db:
    image: postgres
    container_name: postgres
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - .:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_NAME: ${DB_NAME}

  api: 
    container_name: api
    build:
      context: .
    tty: false
    restart: on-failure
    ports:
      - "8000:8000"
    links:
      - db
    depends_on:
      db:
        condition: service_healthy
    command: bash -c "alembic upgrade head & uvicorn src.main:app --host 0.0.0.0"
